version: '3.8'

services:
  scale-server:
    build: .
    container_name: esp32_scale_server
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - TZ=Asia/Kolkata
    restart: unless-stopped
